version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.14.1

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Build package
          command: yarn build
      - run:
          name: Publish package if needed
          command: npm run release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: /^master$/